name: Hello World Javascript
author: Jpinho
description: Some description
inputs: 
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Pinho
outputs: 
  time:
    description: 'The greeting time'
runs: 
  using: 'node12'
  main: 'dist/index.js'