on: push 
jobs: 
  testing-action:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          chmod +X entrypoint.sh
      - uses: ./.github/actions/issue
        id: issue
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          title: title
          body: body
          assignees: |
            joaopinho-git
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      #- uses: ./.github/actions/hello
      - uses: ./.github/actions/hello-docker
        #id: hello
        id: hello-docker
        with:
          who-to-greet: "World"
      - run: |
         echo "Time: ${{ steps.hello.outputs.time }}"
         echo $HELLO