on: push 
jobs: 
  testing-action:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Send a Slack Message: message tal cenas"
        uses: ./.github/actions/slack
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello Slack from PHP Action
      - name: give permissions to SH that came from windows
        run: |
          ls -la
          pwd
          chmod +x ./.github/actions/hello-docker/entrypoint.sh
      - uses: ./.github/actions/issue
        id: issue
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          title: title
          body: body
          assignees: |
            joaopinho-git
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      #- uses: ./.github/actions/hello
      - uses: ./.github/actions/hello-docker
        #id: hello
        id: hello-docker
        with:
          who-to-greet: "World"
      - run: |
         echo "Time: ${{ steps.hello-docker.outputs.time }}"
         echo $HELLO
