name: Actions Workflow

on: 
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs: 
  run-github-changejob:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.1
      - name: File changed rebuild and test
        if: contains(steps.changed-files.outputs.modified_files, 'changeMe.txt')
        run: echo "Call my docker"