name: Slack Notifications
on: 
  pull_request:
    types: [opened, reopened, closed]
    #branches: [develop, master22]

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps: 
      - name: pull_request Message
        run: | 
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Pull Request ${{ github.event.pull_request.number }} ${{ github.event.pull_request.state }} by ${{ github.event.sender.login }}: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>; ${{ github.event.pull_request.body }}"}' ${{ secrets.SLACK_WEBHOOK }}